project:
  type: website
  output-dir: "docs"

website:
  title: "Omotola Ayodele Lawal"
  navbar:
     left:
      - text: "Home"
        href: index.qmd
      - text: "Portfolio"
        href: Portfolio.qmd
      - text: "CV"
        href: CV.qmd
      - text: "Certification"
        href: Cert.qmd
     right:
      - icon: github
        href: https://github.com/lawaloa
      - icon: twitter
        href: https://twitter.com/@LawalOmotola20
 
  sidebar:
   - title: "Portfolio"
     style: "docked"
     background: light
     contents:
        - netflix.qmd
        - conditional.qmd
        - join_pandas.qmd
        - main_dash.qmd
        # navigation items
        
   - title: "Certification"
     contents:
        - Cert.qmd
        - annual.qmd
        # navigation items
        
    
format:
  html:
    theme: quartz
    css: style.css
    toc: true

editor: visual

