project:
  type: website
  output-dir: "docs"

website:
  title: "Omotola Ayodele Lawal"
  navbar:
     left:
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: Portfolio.qmd
      - text: "CV"
        file: CV.qmd
     right:
      - icon: github
        href: https://github.com/lawaloa
      - icon: twitter
        href: https://twitter.com/@LawalOmotola20
format:
  html:
    theme: 
     light: cosmo
     dark: [cosmo, theme-dark.scss]
    css: style.css

editor: visual

